name: dumka
description: 'the Dumka Project'

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # UI
  custom_switch_button: ^0.5.0
  material_design_icons_flutter: ^4.0.5955

  google_fonts: ^2.0.0
  flutter_svg: ^0.19.3
  md2_tab_indicator: ^1.0.2

  firebase_core: ^1.0.1
  firebase_analytics: ^7.1.1
  firebase_crashlytics: ^1.0.0

  dio: ^4.0.0-prev3
  flutter_bloc: ^7.0.0

  # todo use hive + encrypted storage
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  lint: ^1.5.3




flutter:
  uses-material-design: true

  assets:
    - assets/
    - google_fonts/